<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OcrSearch.Core\OcrSearch.Core.csproj" />
    <ProjectReference Include="..\OcrSearch.Ocr.Windows\OcrSearch.Ocr.Windows.csproj" />
  </ItemGroup>

</Project>
